<?php
//通过组合模式输出学校的组织结构

abstract class OrganizationComponent
{
    private $name;  //名字
    private $des;   //描述

    public function __construct($name,$des)
    {
        $this->name = $name;
        $this->name = $des;
    }

    public function setName($name){
        $this->name = $name;
    }

    public function getName(){
        return $this->name;
    }

    public function setDes($des){
        $this->des = $des;
    }

    public function getDes(){
        return $this->des;
    }

    protected function add(OrganizationComponent $organizationComponent){
        throw new Exception('无操作');
    }

    protected function remove(OrganizationComponent $organizationComponent){

    }

    protected abstract function printStr();
}

/**
 * 大学类
 * Class College
 */
class College extends OrganizationComponent{


    //数组中存放Department
    public $OrganizationComponents = [];

    //构造器
    public function __construct($name, $des)
    {
        parent::__construct($name, $des);
    }

    //重写add方法
    protected function add(OrganizationComponent $organizationComponent){
        $this->OrganizationComponents[] = $organizationComponent;
    }

    //重写remove
    protected function remove(OrganizationComponent $organizationComponent){
        $this->OrganizationComponents = array_diff($this->OrganizationComponents,[$organizationComponent]);
    }

    protected function printStr()
    {
        echo '-----------------------'.$this->getName().'----------------------'.PHP_EOL;
        // TODO: Implement printStr() method.
        foreach($this->OrganizationComponents as $v){
            $v->printStr();
        }
    }
}

/**
 * 叶子节点，没有集合
 * Class Department
 */
class Department extends OrganizationComponent{
    public function __construct($name, $des)
    {
        parent::__construct($name, $des);
    }

    //add，remove就不用写了，应为他是叶子节点。

    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }

    public function getDes()
    {
        return parent::getDes(); // TODO: Change the autogenerated stub
    }

    protected function printStr()
    {
        // TODO: Implement printStr() method.
        echo $this->getName().PHP_EOL;
    }


}
